// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: api/id_generator/service/v1/id_generator.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateIdReq) Reset() {
	*x = GenerateIdReq{}
	mi := &file_api_id_generator_service_v1_id_generator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateIdReq) ProtoMessage() {}

func (x *GenerateIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_id_generator_service_v1_id_generator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateIdReq.ProtoReflect.Descriptor instead.
func (*GenerateIdReq) Descriptor() ([]byte, []int) {
	return file_api_id_generator_service_v1_id_generator_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateIdReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GenerateIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                             // 生成的ID
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`               // ID中包含的时间戳（毫秒）
	WorkerId      int32                  `protobuf:"varint,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"` // 工作节点ID
	Sequence      int32                  `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`                 // 序列号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateIdResp) Reset() {
	*x = GenerateIdResp{}
	mi := &file_api_id_generator_service_v1_id_generator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateIdResp) ProtoMessage() {}

func (x *GenerateIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_id_generator_service_v1_id_generator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateIdResp.ProtoReflect.Descriptor instead.
func (*GenerateIdResp) Descriptor() ([]byte, []int) {
	return file_api_id_generator_service_v1_id_generator_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateIdResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GenerateIdResp) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GenerateIdResp) GetWorkerId() int32 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

func (x *GenerateIdResp) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// 批量生成ID请求
type GenerateBatchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint32                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"` // 需要生成的ID数量（建议1-1000）
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`    // ID类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateBatchReq) Reset() {
	*x = GenerateBatchReq{}
	mi := &file_api_id_generator_service_v1_id_generator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateBatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateBatchReq) ProtoMessage() {}

func (x *GenerateBatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_id_generator_service_v1_id_generator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateBatchReq.ProtoReflect.Descriptor instead.
func (*GenerateBatchReq) Descriptor() ([]byte, []int) {
	return file_api_id_generator_service_v1_id_generator_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateBatchReq) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GenerateBatchReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// 批量生成ID响应
type GenerateBatchResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ids            []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`                                        // 生成的ID列表
	Details        []*IdDetail            `protobuf:"bytes,2,rep,name=details,proto3" json:"details,omitempty"`                                        // 每个ID的详细信息（可选）
	GenerateTimeMs int64                  `protobuf:"varint,3,opt,name=generate_time_ms,json=generateTimeMs,proto3" json:"generate_time_ms,omitempty"` // 生成耗时（毫秒）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateBatchResp) Reset() {
	*x = GenerateBatchResp{}
	mi := &file_api_id_generator_service_v1_id_generator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateBatchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateBatchResp) ProtoMessage() {}

func (x *GenerateBatchResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_id_generator_service_v1_id_generator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateBatchResp.ProtoReflect.Descriptor instead.
func (*GenerateBatchResp) Descriptor() ([]byte, []int) {
	return file_api_id_generator_service_v1_id_generator_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateBatchResp) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *GenerateBatchResp) GetDetails() []*IdDetail {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *GenerateBatchResp) GetGenerateTimeMs() int64 {
	if x != nil {
		return x.GenerateTimeMs
	}
	return 0
}

// ID详细信息
type IdDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	WorkerId      int32                  `protobuf:"varint,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Sequence      int32                  `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdDetail) Reset() {
	*x = IdDetail{}
	mi := &file_api_id_generator_service_v1_id_generator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdDetail) ProtoMessage() {}

func (x *IdDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_id_generator_service_v1_id_generator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdDetail.ProtoReflect.Descriptor instead.
func (*IdDetail) Descriptor() ([]byte, []int) {
	return file_api_id_generator_service_v1_id_generator_proto_rawDescGZIP(), []int{4}
}

func (x *IdDetail) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IdDetail) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *IdDetail) GetWorkerId() int32 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

func (x *IdDetail) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

var File_api_id_generator_service_v1_id_generator_proto protoreflect.FileDescriptor

const file_api_id_generator_service_v1_id_generator_proto_rawDesc = "" +
	"\n" +
	".api/id_generator/service/v1/id_generator.proto\x12\x1bapi.id_generator.service.v1\"#\n" +
	"\rGenerateIdReq\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\"w\n" +
	"\x0eGenerateIdResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\x05R\bworkerId\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x05R\bsequence\"<\n" +
	"\x10GenerateBatchReq\x12\x14\n" +
	"\x05count\x18\x01 \x01(\rR\x05count\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\x90\x01\n" +
	"\x11GenerateBatchResp\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\x12?\n" +
	"\adetails\x18\x02 \x03(\v2%.api.id_generator.service.v1.IdDetailR\adetails\x12(\n" +
	"\x10generate_time_ms\x18\x03 \x01(\x03R\x0egenerateTimeMs\"q\n" +
	"\bIdDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\x05R\bworkerId\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x05R\bsequence2\xe4\x01\n" +
	"\vIdGenerator\x12e\n" +
	"\n" +
	"GenerateId\x12*.api.id_generator.service.v1.GenerateIdReq\x1a+.api.id_generator.service.v1.GenerateIdResp\x12n\n" +
	"\rGenerateBatch\x12-.api.id_generator.service.v1.GenerateBatchReq\x1a..api.id_generator.service.v1.GenerateBatchRespBP\n" +
	"\x1bapi.id_generator.service.v1P\x01Z/lehu-data-center/api/id_generator/service/v1;v1b\x06proto3"

var (
	file_api_id_generator_service_v1_id_generator_proto_rawDescOnce sync.Once
	file_api_id_generator_service_v1_id_generator_proto_rawDescData []byte
)

func file_api_id_generator_service_v1_id_generator_proto_rawDescGZIP() []byte {
	file_api_id_generator_service_v1_id_generator_proto_rawDescOnce.Do(func() {
		file_api_id_generator_service_v1_id_generator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_id_generator_service_v1_id_generator_proto_rawDesc), len(file_api_id_generator_service_v1_id_generator_proto_rawDesc)))
	})
	return file_api_id_generator_service_v1_id_generator_proto_rawDescData
}

var file_api_id_generator_service_v1_id_generator_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_id_generator_service_v1_id_generator_proto_goTypes = []any{
	(*GenerateIdReq)(nil),     // 0: api.id_generator.service.v1.GenerateIdReq
	(*GenerateIdResp)(nil),    // 1: api.id_generator.service.v1.GenerateIdResp
	(*GenerateBatchReq)(nil),  // 2: api.id_generator.service.v1.GenerateBatchReq
	(*GenerateBatchResp)(nil), // 3: api.id_generator.service.v1.GenerateBatchResp
	(*IdDetail)(nil),          // 4: api.id_generator.service.v1.IdDetail
}
var file_api_id_generator_service_v1_id_generator_proto_depIdxs = []int32{
	4, // 0: api.id_generator.service.v1.GenerateBatchResp.details:type_name -> api.id_generator.service.v1.IdDetail
	0, // 1: api.id_generator.service.v1.IdGenerator.GenerateId:input_type -> api.id_generator.service.v1.GenerateIdReq
	2, // 2: api.id_generator.service.v1.IdGenerator.GenerateBatch:input_type -> api.id_generator.service.v1.GenerateBatchReq
	1, // 3: api.id_generator.service.v1.IdGenerator.GenerateId:output_type -> api.id_generator.service.v1.GenerateIdResp
	3, // 4: api.id_generator.service.v1.IdGenerator.GenerateBatch:output_type -> api.id_generator.service.v1.GenerateBatchResp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_id_generator_service_v1_id_generator_proto_init() }
func file_api_id_generator_service_v1_id_generator_proto_init() {
	if File_api_id_generator_service_v1_id_generator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_id_generator_service_v1_id_generator_proto_rawDesc), len(file_api_id_generator_service_v1_id_generator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_id_generator_service_v1_id_generator_proto_goTypes,
		DependencyIndexes: file_api_id_generator_service_v1_id_generator_proto_depIdxs,
		MessageInfos:      file_api_id_generator_service_v1_id_generator_proto_msgTypes,
	}.Build()
	File_api_id_generator_service_v1_id_generator_proto = out.File
	file_api_id_generator_service_v1_id_generator_proto_goTypes = nil
	file_api_id_generator_service_v1_id_generator_proto_depIdxs = nil
}
