// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: api/id_generator/service/v1/id_generator.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IdGenerator_GenerateId_FullMethodName    = "/api.id_generator.service.v1.IdGenerator/GenerateId"
	IdGenerator_GenerateBatch_FullMethodName = "/api.id_generator.service.v1.IdGenerator/GenerateBatch"
)

// IdGeneratorClient is the client API for IdGenerator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// id生成服务
type IdGeneratorClient interface {
	// 生成单个id
	GenerateId(ctx context.Context, in *GenerateIdReq, opts ...grpc.CallOption) (*GenerateIdResp, error)
	// 批量生成id
	GenerateBatch(ctx context.Context, in *GenerateBatchReq, opts ...grpc.CallOption) (*GenerateBatchResp, error)
}

type idGeneratorClient struct {
	cc grpc.ClientConnInterface
}

func NewIdGeneratorClient(cc grpc.ClientConnInterface) IdGeneratorClient {
	return &idGeneratorClient{cc}
}

func (c *idGeneratorClient) GenerateId(ctx context.Context, in *GenerateIdReq, opts ...grpc.CallOption) (*GenerateIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateIdResp)
	err := c.cc.Invoke(ctx, IdGenerator_GenerateId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *idGeneratorClient) GenerateBatch(ctx context.Context, in *GenerateBatchReq, opts ...grpc.CallOption) (*GenerateBatchResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateBatchResp)
	err := c.cc.Invoke(ctx, IdGenerator_GenerateBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdGeneratorServer is the server API for IdGenerator service.
// All implementations must embed UnimplementedIdGeneratorServer
// for forward compatibility.
//
// id生成服务
type IdGeneratorServer interface {
	// 生成单个id
	GenerateId(context.Context, *GenerateIdReq) (*GenerateIdResp, error)
	// 批量生成id
	GenerateBatch(context.Context, *GenerateBatchReq) (*GenerateBatchResp, error)
	mustEmbedUnimplementedIdGeneratorServer()
}

// UnimplementedIdGeneratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdGeneratorServer struct{}

func (UnimplementedIdGeneratorServer) GenerateId(context.Context, *GenerateIdReq) (*GenerateIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateId not implemented")
}
func (UnimplementedIdGeneratorServer) GenerateBatch(context.Context, *GenerateBatchReq) (*GenerateBatchResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateBatch not implemented")
}
func (UnimplementedIdGeneratorServer) mustEmbedUnimplementedIdGeneratorServer() {}
func (UnimplementedIdGeneratorServer) testEmbeddedByValue()                     {}

// UnsafeIdGeneratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdGeneratorServer will
// result in compilation errors.
type UnsafeIdGeneratorServer interface {
	mustEmbedUnimplementedIdGeneratorServer()
}

func RegisterIdGeneratorServer(s grpc.ServiceRegistrar, srv IdGeneratorServer) {
	// If the following call pancis, it indicates UnimplementedIdGeneratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdGenerator_ServiceDesc, srv)
}

func _IdGenerator_GenerateId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdGeneratorServer).GenerateId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdGenerator_GenerateId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdGeneratorServer).GenerateId(ctx, req.(*GenerateIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdGenerator_GenerateBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateBatchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdGeneratorServer).GenerateBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdGenerator_GenerateBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdGeneratorServer).GenerateBatch(ctx, req.(*GenerateBatchReq))
	}
	return interceptor(ctx, in, info, handler)
}

// IdGenerator_ServiceDesc is the grpc.ServiceDesc for IdGenerator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdGenerator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.id_generator.service.v1.IdGenerator",
	HandlerType: (*IdGeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateId",
			Handler:    _IdGenerator_GenerateId_Handler,
		},
		{
			MethodName: "GenerateBatch",
			Handler:    _IdGenerator_GenerateBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/id_generator/service/v1/id_generator.proto",
}
