// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"lehu-data-center/app/collect/service/internal/biz"
	"lehu-data-center/app/collect/service/internal/conf"
	"lehu-data-center/app/collect/service/internal/data"
	"lehu-data-center/app/collect/service/internal/server"
	"lehu-data-center/app/collect/service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData, logger)
	discovery := data.NewDiscovery(registry)
	idGeneratorClient := data.NewIdGeneratorClient(discovery)
	agilityDataClient := data.NewAgilityDataClient(discovery)
	dataData, cleanup, err := data.NewData(confData, db, idGeneratorClient, agilityDataClient, logger)
	if err != nil {
		return nil, nil, err
	}
	collectRepo := data.NewCollectRepo(dataData, logger)
	collectUsecase := biz.NewCollectUsecase(collectRepo, logger)
	collectService := service.NewCollectService(collectUsecase)
	grpcServer := server.NewGRPCServer(confServer, collectService, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
