// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"lehu-data-center/app/agility_data/service/internal/biz"
	"lehu-data-center/app/agility_data/service/internal/conf"
	"lehu-data-center/app/agility_data/service/internal/data"
	"lehu-data-center/app/agility_data/service/internal/server"
	"lehu-data-center/app/agility_data/service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	agilityRepo := data.NewAgilityRepo(dataData, logger)
	agilityUsecase := biz.NewAgilityUsecase(agilityRepo, logger)
	agilityDataService := service.NewAgilityDataService(agilityUsecase)
	grpcServer := server.NewGRPCServer(confServer, agilityDataService, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
