// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: api/collect/service/v1/collect.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Collect_CreateCollect_FullMethodName = "/api.collect.service.v1.Collect/CreateCollect"
	Collect_UpdateCollect_FullMethodName = "/api.collect.service.v1.Collect/UpdateCollect"
	Collect_DeleteCollect_FullMethodName = "/api.collect.service.v1.Collect/DeleteCollect"
	Collect_GetCollect_FullMethodName    = "/api.collect.service.v1.Collect/GetCollect"
	Collect_ListCollect_FullMethodName   = "/api.collect.service.v1.Collect/ListCollect"
)

// CollectClient is the client API for Collect service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CollectClient interface {
	CreateCollect(ctx context.Context, in *CreateCollectRequest, opts ...grpc.CallOption) (*CreateCollectReply, error)
	UpdateCollect(ctx context.Context, in *UpdateCollectRequest, opts ...grpc.CallOption) (*UpdateCollectReply, error)
	DeleteCollect(ctx context.Context, in *DeleteCollectRequest, opts ...grpc.CallOption) (*DeleteCollectReply, error)
	GetCollect(ctx context.Context, in *GetCollectRequest, opts ...grpc.CallOption) (*GetCollectReply, error)
	ListCollect(ctx context.Context, in *ListCollectRequest, opts ...grpc.CallOption) (*ListCollectReply, error)
}

type collectClient struct {
	cc grpc.ClientConnInterface
}

func NewCollectClient(cc grpc.ClientConnInterface) CollectClient {
	return &collectClient{cc}
}

func (c *collectClient) CreateCollect(ctx context.Context, in *CreateCollectRequest, opts ...grpc.CallOption) (*CreateCollectReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCollectReply)
	err := c.cc.Invoke(ctx, Collect_CreateCollect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectClient) UpdateCollect(ctx context.Context, in *UpdateCollectRequest, opts ...grpc.CallOption) (*UpdateCollectReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCollectReply)
	err := c.cc.Invoke(ctx, Collect_UpdateCollect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectClient) DeleteCollect(ctx context.Context, in *DeleteCollectRequest, opts ...grpc.CallOption) (*DeleteCollectReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCollectReply)
	err := c.cc.Invoke(ctx, Collect_DeleteCollect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectClient) GetCollect(ctx context.Context, in *GetCollectRequest, opts ...grpc.CallOption) (*GetCollectReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCollectReply)
	err := c.cc.Invoke(ctx, Collect_GetCollect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectClient) ListCollect(ctx context.Context, in *ListCollectRequest, opts ...grpc.CallOption) (*ListCollectReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCollectReply)
	err := c.cc.Invoke(ctx, Collect_ListCollect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CollectServer is the server API for Collect service.
// All implementations must embed UnimplementedCollectServer
// for forward compatibility.
type CollectServer interface {
	CreateCollect(context.Context, *CreateCollectRequest) (*CreateCollectReply, error)
	UpdateCollect(context.Context, *UpdateCollectRequest) (*UpdateCollectReply, error)
	DeleteCollect(context.Context, *DeleteCollectRequest) (*DeleteCollectReply, error)
	GetCollect(context.Context, *GetCollectRequest) (*GetCollectReply, error)
	ListCollect(context.Context, *ListCollectRequest) (*ListCollectReply, error)
	mustEmbedUnimplementedCollectServer()
}

// UnimplementedCollectServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCollectServer struct{}

func (UnimplementedCollectServer) CreateCollect(context.Context, *CreateCollectRequest) (*CreateCollectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCollect not implemented")
}
func (UnimplementedCollectServer) UpdateCollect(context.Context, *UpdateCollectRequest) (*UpdateCollectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCollect not implemented")
}
func (UnimplementedCollectServer) DeleteCollect(context.Context, *DeleteCollectRequest) (*DeleteCollectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCollect not implemented")
}
func (UnimplementedCollectServer) GetCollect(context.Context, *GetCollectRequest) (*GetCollectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCollect not implemented")
}
func (UnimplementedCollectServer) ListCollect(context.Context, *ListCollectRequest) (*ListCollectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCollect not implemented")
}
func (UnimplementedCollectServer) mustEmbedUnimplementedCollectServer() {}
func (UnimplementedCollectServer) testEmbeddedByValue()                 {}

// UnsafeCollectServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CollectServer will
// result in compilation errors.
type UnsafeCollectServer interface {
	mustEmbedUnimplementedCollectServer()
}

func RegisterCollectServer(s grpc.ServiceRegistrar, srv CollectServer) {
	// If the following call pancis, it indicates UnimplementedCollectServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Collect_ServiceDesc, srv)
}

func _Collect_CreateCollect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCollectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectServer).CreateCollect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Collect_CreateCollect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectServer).CreateCollect(ctx, req.(*CreateCollectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Collect_UpdateCollect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCollectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectServer).UpdateCollect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Collect_UpdateCollect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectServer).UpdateCollect(ctx, req.(*UpdateCollectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Collect_DeleteCollect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCollectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectServer).DeleteCollect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Collect_DeleteCollect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectServer).DeleteCollect(ctx, req.(*DeleteCollectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Collect_GetCollect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectServer).GetCollect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Collect_GetCollect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectServer).GetCollect(ctx, req.(*GetCollectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Collect_ListCollect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCollectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectServer).ListCollect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Collect_ListCollect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectServer).ListCollect(ctx, req.(*ListCollectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Collect_ServiceDesc is the grpc.ServiceDesc for Collect service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Collect_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.collect.service.v1.Collect",
	HandlerType: (*CollectServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCollect",
			Handler:    _Collect_CreateCollect_Handler,
		},
		{
			MethodName: "UpdateCollect",
			Handler:    _Collect_UpdateCollect_Handler,
		},
		{
			MethodName: "DeleteCollect",
			Handler:    _Collect_DeleteCollect_Handler,
		},
		{
			MethodName: "GetCollect",
			Handler:    _Collect_GetCollect_Handler,
		},
		{
			MethodName: "ListCollect",
			Handler:    _Collect_ListCollect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/collect/service/v1/collect.proto",
}
