// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: api/collect/service/v1/collect.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCollectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectRequest) Reset() {
	*x = CreateCollectRequest{}
	mi := &file_api_collect_service_v1_collect_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectRequest) ProtoMessage() {}

func (x *CreateCollectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_collect_service_v1_collect_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectRequest.ProtoReflect.Descriptor instead.
func (*CreateCollectRequest) Descriptor() ([]byte, []int) {
	return file_api_collect_service_v1_collect_proto_rawDescGZIP(), []int{0}
}

type CreateCollectReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectReply) Reset() {
	*x = CreateCollectReply{}
	mi := &file_api_collect_service_v1_collect_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectReply) ProtoMessage() {}

func (x *CreateCollectReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_collect_service_v1_collect_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectReply.ProtoReflect.Descriptor instead.
func (*CreateCollectReply) Descriptor() ([]byte, []int) {
	return file_api_collect_service_v1_collect_proto_rawDescGZIP(), []int{1}
}

type UpdateCollectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCollectRequest) Reset() {
	*x = UpdateCollectRequest{}
	mi := &file_api_collect_service_v1_collect_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCollectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCollectRequest) ProtoMessage() {}

func (x *UpdateCollectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_collect_service_v1_collect_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCollectRequest.ProtoReflect.Descriptor instead.
func (*UpdateCollectRequest) Descriptor() ([]byte, []int) {
	return file_api_collect_service_v1_collect_proto_rawDescGZIP(), []int{2}
}

type UpdateCollectReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCollectReply) Reset() {
	*x = UpdateCollectReply{}
	mi := &file_api_collect_service_v1_collect_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCollectReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCollectReply) ProtoMessage() {}

func (x *UpdateCollectReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_collect_service_v1_collect_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCollectReply.ProtoReflect.Descriptor instead.
func (*UpdateCollectReply) Descriptor() ([]byte, []int) {
	return file_api_collect_service_v1_collect_proto_rawDescGZIP(), []int{3}
}

type DeleteCollectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCollectRequest) Reset() {
	*x = DeleteCollectRequest{}
	mi := &file_api_collect_service_v1_collect_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCollectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCollectRequest) ProtoMessage() {}

func (x *DeleteCollectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_collect_service_v1_collect_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCollectRequest.ProtoReflect.Descriptor instead.
func (*DeleteCollectRequest) Descriptor() ([]byte, []int) {
	return file_api_collect_service_v1_collect_proto_rawDescGZIP(), []int{4}
}

type DeleteCollectReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCollectReply) Reset() {
	*x = DeleteCollectReply{}
	mi := &file_api_collect_service_v1_collect_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCollectReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCollectReply) ProtoMessage() {}

func (x *DeleteCollectReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_collect_service_v1_collect_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCollectReply.ProtoReflect.Descriptor instead.
func (*DeleteCollectReply) Descriptor() ([]byte, []int) {
	return file_api_collect_service_v1_collect_proto_rawDescGZIP(), []int{5}
}

type GetCollectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollectRequest) Reset() {
	*x = GetCollectRequest{}
	mi := &file_api_collect_service_v1_collect_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectRequest) ProtoMessage() {}

func (x *GetCollectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_collect_service_v1_collect_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectRequest.ProtoReflect.Descriptor instead.
func (*GetCollectRequest) Descriptor() ([]byte, []int) {
	return file_api_collect_service_v1_collect_proto_rawDescGZIP(), []int{6}
}

type GetCollectReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollectReply) Reset() {
	*x = GetCollectReply{}
	mi := &file_api_collect_service_v1_collect_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectReply) ProtoMessage() {}

func (x *GetCollectReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_collect_service_v1_collect_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectReply.ProtoReflect.Descriptor instead.
func (*GetCollectReply) Descriptor() ([]byte, []int) {
	return file_api_collect_service_v1_collect_proto_rawDescGZIP(), []int{7}
}

type ListCollectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectRequest) Reset() {
	*x = ListCollectRequest{}
	mi := &file_api_collect_service_v1_collect_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectRequest) ProtoMessage() {}

func (x *ListCollectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_collect_service_v1_collect_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectRequest.ProtoReflect.Descriptor instead.
func (*ListCollectRequest) Descriptor() ([]byte, []int) {
	return file_api_collect_service_v1_collect_proto_rawDescGZIP(), []int{8}
}

type ListCollectReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectReply) Reset() {
	*x = ListCollectReply{}
	mi := &file_api_collect_service_v1_collect_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectReply) ProtoMessage() {}

func (x *ListCollectReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_collect_service_v1_collect_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectReply.ProtoReflect.Descriptor instead.
func (*ListCollectReply) Descriptor() ([]byte, []int) {
	return file_api_collect_service_v1_collect_proto_rawDescGZIP(), []int{9}
}

var File_api_collect_service_v1_collect_proto protoreflect.FileDescriptor

const file_api_collect_service_v1_collect_proto_rawDesc = "" +
	"\n" +
	"$api/collect/service/v1/collect.proto\x12\x16api.collect.service.v1\"\x16\n" +
	"\x14CreateCollectRequest\"\x14\n" +
	"\x12CreateCollectReply\"\x16\n" +
	"\x14UpdateCollectRequest\"\x14\n" +
	"\x12UpdateCollectReply\"\x16\n" +
	"\x14DeleteCollectRequest\"\x14\n" +
	"\x12DeleteCollectReply\"\x13\n" +
	"\x11GetCollectRequest\"\x11\n" +
	"\x0fGetCollectReply\"\x14\n" +
	"\x12ListCollectRequest\"\x12\n" +
	"\x10ListCollectReply2\x91\x04\n" +
	"\aCollect\x12i\n" +
	"\rCreateCollect\x12,.api.collect.service.v1.CreateCollectRequest\x1a*.api.collect.service.v1.CreateCollectReply\x12i\n" +
	"\rUpdateCollect\x12,.api.collect.service.v1.UpdateCollectRequest\x1a*.api.collect.service.v1.UpdateCollectReply\x12i\n" +
	"\rDeleteCollect\x12,.api.collect.service.v1.DeleteCollectRequest\x1a*.api.collect.service.v1.DeleteCollectReply\x12`\n" +
	"\n" +
	"GetCollect\x12).api.collect.service.v1.GetCollectRequest\x1a'.api.collect.service.v1.GetCollectReply\x12c\n" +
	"\vListCollect\x12*.api.collect.service.v1.ListCollectRequest\x1a(.api.collect.service.v1.ListCollectReplyBF\n" +
	"\x16api.collect.service.v1P\x01Z*lehu-data-center/api/collect/service/v1;v1b\x06proto3"

var (
	file_api_collect_service_v1_collect_proto_rawDescOnce sync.Once
	file_api_collect_service_v1_collect_proto_rawDescData []byte
)

func file_api_collect_service_v1_collect_proto_rawDescGZIP() []byte {
	file_api_collect_service_v1_collect_proto_rawDescOnce.Do(func() {
		file_api_collect_service_v1_collect_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_collect_service_v1_collect_proto_rawDesc), len(file_api_collect_service_v1_collect_proto_rawDesc)))
	})
	return file_api_collect_service_v1_collect_proto_rawDescData
}

var file_api_collect_service_v1_collect_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_collect_service_v1_collect_proto_goTypes = []any{
	(*CreateCollectRequest)(nil), // 0: api.collect.service.v1.CreateCollectRequest
	(*CreateCollectReply)(nil),   // 1: api.collect.service.v1.CreateCollectReply
	(*UpdateCollectRequest)(nil), // 2: api.collect.service.v1.UpdateCollectRequest
	(*UpdateCollectReply)(nil),   // 3: api.collect.service.v1.UpdateCollectReply
	(*DeleteCollectRequest)(nil), // 4: api.collect.service.v1.DeleteCollectRequest
	(*DeleteCollectReply)(nil),   // 5: api.collect.service.v1.DeleteCollectReply
	(*GetCollectRequest)(nil),    // 6: api.collect.service.v1.GetCollectRequest
	(*GetCollectReply)(nil),      // 7: api.collect.service.v1.GetCollectReply
	(*ListCollectRequest)(nil),   // 8: api.collect.service.v1.ListCollectRequest
	(*ListCollectReply)(nil),     // 9: api.collect.service.v1.ListCollectReply
}
var file_api_collect_service_v1_collect_proto_depIdxs = []int32{
	0, // 0: api.collect.service.v1.Collect.CreateCollect:input_type -> api.collect.service.v1.CreateCollectRequest
	2, // 1: api.collect.service.v1.Collect.UpdateCollect:input_type -> api.collect.service.v1.UpdateCollectRequest
	4, // 2: api.collect.service.v1.Collect.DeleteCollect:input_type -> api.collect.service.v1.DeleteCollectRequest
	6, // 3: api.collect.service.v1.Collect.GetCollect:input_type -> api.collect.service.v1.GetCollectRequest
	8, // 4: api.collect.service.v1.Collect.ListCollect:input_type -> api.collect.service.v1.ListCollectRequest
	1, // 5: api.collect.service.v1.Collect.CreateCollect:output_type -> api.collect.service.v1.CreateCollectReply
	3, // 6: api.collect.service.v1.Collect.UpdateCollect:output_type -> api.collect.service.v1.UpdateCollectReply
	5, // 7: api.collect.service.v1.Collect.DeleteCollect:output_type -> api.collect.service.v1.DeleteCollectReply
	7, // 8: api.collect.service.v1.Collect.GetCollect:output_type -> api.collect.service.v1.GetCollectReply
	9, // 9: api.collect.service.v1.Collect.ListCollect:output_type -> api.collect.service.v1.ListCollectReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_collect_service_v1_collect_proto_init() }
func file_api_collect_service_v1_collect_proto_init() {
	if File_api_collect_service_v1_collect_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_collect_service_v1_collect_proto_rawDesc), len(file_api_collect_service_v1_collect_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_collect_service_v1_collect_proto_goTypes,
		DependencyIndexes: file_api_collect_service_v1_collect_proto_depIdxs,
		MessageInfos:      file_api_collect_service_v1_collect_proto_msgTypes,
	}.Build()
	File_api_collect_service_v1_collect_proto = out.File
	file_api_collect_service_v1_collect_proto_goTypes = nil
	file_api_collect_service_v1_collect_proto_depIdxs = nil
}
