// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: api/agility_data/service/v1/agility_data.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NullValue 空值
type NullValue int32

const (
	NullValue_NULL_VALUE NullValue = 0
)

// Enum value maps for NullValue.
var (
	NullValue_name = map[int32]string{
		0: "NULL_VALUE",
	}
	NullValue_value = map[string]int32{
		"NULL_VALUE": 0,
	}
)

func (x NullValue) Enum() *NullValue {
	p := new(NullValue)
	*p = x
	return p
}

func (x NullValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NullValue) Descriptor() protoreflect.EnumDescriptor {
	return file_api_agility_data_service_v1_agility_data_proto_enumTypes[0].Descriptor()
}

func (NullValue) Type() protoreflect.EnumType {
	return &file_api_agility_data_service_v1_agility_data_proto_enumTypes[0]
}

func (x NullValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NullValue.Descriptor instead.
func (NullValue) EnumDescriptor() ([]byte, []int) {
	return file_api_agility_data_service_v1_agility_data_proto_rawDescGZIP(), []int{0}
}

// ListRequest 列表查询请求
type ListRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Sql            string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`                                                                                 // SQL语句
	DataSourceName string                 `protobuf:"bytes,2,opt,name=data_source_name,json=dataSourceName,proto3" json:"data_source_name,omitempty"`                                   // 数据源名称
	Params         map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 查询参数
	Page           int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`                                                                              // 页码
	PageSize       int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`                                                      // 每页大小
	ResultType     string                 `protobuf:"bytes,6,opt,name=result_type,json=resultType,proto3" json:"result_type,omitempty"`                                                 // 结果类型（可选）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_api_agility_data_service_v1_agility_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agility_data_service_v1_agility_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_api_agility_data_service_v1_agility_data_proto_rawDescGZIP(), []int{0}
}

func (x *ListRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *ListRequest) GetDataSourceName() string {
	if x != nil {
		return x.DataSourceName
	}
	return ""
}

func (x *ListRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRequest) GetResultType() string {
	if x != nil {
		return x.ResultType
	}
	return ""
}

// ListResponse 列表查询响应
type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Record              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`                               // 记录列表
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`      // 总记录数
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                                    // 当前页码
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`            // 每页大小
	TotalPages    int32                  `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`      // 总页数
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 错误信息
	Success       bool                   `protobuf:"varint,7,opt,name=success,proto3" json:"success,omitempty"`                              // 是否成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_api_agility_data_service_v1_agility_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_agility_data_service_v1_agility_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_api_agility_data_service_v1_agility_data_proto_rawDescGZIP(), []int{1}
}

func (x *ListResponse) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *ListResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *ListResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ListResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// GetRequest 单条查询请求
type GetRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Sql            string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	DataSourceName string                 `protobuf:"bytes,2,opt,name=data_source_name,json=dataSourceName,proto3" json:"data_source_name,omitempty"`
	Params         map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_agility_data_service_v1_agility_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agility_data_service_v1_agility_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_agility_data_service_v1_agility_data_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *GetRequest) GetDataSourceName() string {
	if x != nil {
		return x.DataSourceName
	}
	return ""
}

func (x *GetRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

// GetResponse 单条查询响应
type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *Record                `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_api_agility_data_service_v1_agility_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_agility_data_service_v1_agility_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_api_agility_data_service_v1_agility_data_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *GetResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ExecuteRequest 执行请求
type ExecuteRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Sql                 string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	DataSourceName      string                 `protobuf:"bytes,2,opt,name=data_source_name,json=dataSourceName,proto3" json:"data_source_name,omitempty"`
	Params              map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ReturnGeneratedKeys bool                   `protobuf:"varint,4,opt,name=return_generated_keys,json=returnGeneratedKeys,proto3" json:"return_generated_keys,omitempty"` // 是否返回生成的主键
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_api_agility_data_service_v1_agility_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agility_data_service_v1_agility_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_api_agility_data_service_v1_agility_data_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *ExecuteRequest) GetDataSourceName() string {
	if x != nil {
		return x.DataSourceName
	}
	return ""
}

func (x *ExecuteRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ExecuteRequest) GetReturnGeneratedKeys() bool {
	if x != nil {
		return x.ReturnGeneratedKeys
	}
	return false
}

// ExecuteResponse 执行响应
type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RowsAffected  int64                  `protobuf:"varint,1,opt,name=rows_affected,json=rowsAffected,proto3" json:"rows_affected,omitempty"`           // 影响的行数
	GeneratedKeys []int64                `protobuf:"varint,2,rep,packed,name=generated_keys,json=generatedKeys,proto3" json:"generated_keys,omitempty"` // 生成的主键
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_api_agility_data_service_v1_agility_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_agility_data_service_v1_agility_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_api_agility_data_service_v1_agility_data_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteResponse) GetRowsAffected() int64 {
	if x != nil {
		return x.RowsAffected
	}
	return 0
}

func (x *ExecuteResponse) GetGeneratedKeys() []int64 {
	if x != nil {
		return x.GeneratedKeys
	}
	return nil
}

func (x *ExecuteResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ExecuteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 用于BatchExecuteRequest的参数映射
type ParamsMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        map[string]string      `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamsMap) Reset() {
	*x = ParamsMap{}
	mi := &file_api_agility_data_service_v1_agility_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamsMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamsMap) ProtoMessage() {}

func (x *ParamsMap) ProtoReflect() protoreflect.Message {
	mi := &file_api_agility_data_service_v1_agility_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamsMap.ProtoReflect.Descriptor instead.
func (*ParamsMap) Descriptor() ([]byte, []int) {
	return file_api_agility_data_service_v1_agility_data_proto_rawDescGZIP(), []int{6}
}

func (x *ParamsMap) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

// BatchExecuteRequest 批量执行请求
type BatchExecuteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Sql            string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	DataSourceName string                 `protobuf:"bytes,2,opt,name=data_source_name,json=dataSourceName,proto3" json:"data_source_name,omitempty"`
	ParamsList     []*ParamsMap           `protobuf:"bytes,3,rep,name=params_list,json=paramsList,proto3" json:"params_list,omitempty"` // 使用嵌套消息代替repeated map
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchExecuteRequest) Reset() {
	*x = BatchExecuteRequest{}
	mi := &file_api_agility_data_service_v1_agility_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchExecuteRequest) ProtoMessage() {}

func (x *BatchExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agility_data_service_v1_agility_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchExecuteRequest.ProtoReflect.Descriptor instead.
func (*BatchExecuteRequest) Descriptor() ([]byte, []int) {
	return file_api_agility_data_service_v1_agility_data_proto_rawDescGZIP(), []int{7}
}

func (x *BatchExecuteRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *BatchExecuteRequest) GetDataSourceName() string {
	if x != nil {
		return x.DataSourceName
	}
	return ""
}

func (x *BatchExecuteRequest) GetParamsList() []*ParamsMap {
	if x != nil {
		return x.ParamsList
	}
	return nil
}

// BatchExecuteResponse 批量执行响应
type BatchExecuteResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RowsAffectedList []int64                `protobuf:"varint,1,rep,packed,name=rows_affected_list,json=rowsAffectedList,proto3" json:"rows_affected_list,omitempty"` // 每条SQL影响的行数
	ErrorMessage     string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Success          bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BatchExecuteResponse) Reset() {
	*x = BatchExecuteResponse{}
	mi := &file_api_agility_data_service_v1_agility_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchExecuteResponse) ProtoMessage() {}

func (x *BatchExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_agility_data_service_v1_agility_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchExecuteResponse.ProtoReflect.Descriptor instead.
func (*BatchExecuteResponse) Descriptor() ([]byte, []int) {
	return file_api_agility_data_service_v1_agility_data_proto_rawDescGZIP(), []int{8}
}

func (x *BatchExecuteResponse) GetRowsAffectedList() []int64 {
	if x != nil {
		return x.RowsAffectedList
	}
	return nil
}

func (x *BatchExecuteResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *BatchExecuteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// TestConnectionRequest 测试连接请求
type TestConnectionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DataSourceName string                 `protobuf:"bytes,1,opt,name=data_source_name,json=dataSourceName,proto3" json:"data_source_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TestConnectionRequest) Reset() {
	*x = TestConnectionRequest{}
	mi := &file_api_agility_data_service_v1_agility_data_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConnectionRequest) ProtoMessage() {}

func (x *TestConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agility_data_service_v1_agility_data_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConnectionRequest.ProtoReflect.Descriptor instead.
func (*TestConnectionRequest) Descriptor() ([]byte, []int) {
	return file_api_agility_data_service_v1_agility_data_proto_rawDescGZIP(), []int{9}
}

func (x *TestConnectionRequest) GetDataSourceName() string {
	if x != nil {
		return x.DataSourceName
	}
	return ""
}

// TestConnectionResponse 测试连接响应
type TestConnectionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Connected      bool                   `protobuf:"varint,1,opt,name=connected,proto3" json:"connected,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ResponseTimeMs int64                  `protobuf:"varint,3,opt,name=response_time_ms,json=responseTimeMs,proto3" json:"response_time_ms,omitempty"` // 响应时间(毫秒)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TestConnectionResponse) Reset() {
	*x = TestConnectionResponse{}
	mi := &file_api_agility_data_service_v1_agility_data_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConnectionResponse) ProtoMessage() {}

func (x *TestConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_agility_data_service_v1_agility_data_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConnectionResponse.ProtoReflect.Descriptor instead.
func (*TestConnectionResponse) Descriptor() ([]byte, []int) {
	return file_api_agility_data_service_v1_agility_data_proto_rawDescGZIP(), []int{10}
}

func (x *TestConnectionResponse) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *TestConnectionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TestConnectionResponse) GetResponseTimeMs() int64 {
	if x != nil {
		return x.ResponseTimeMs
	}
	return 0
}

// Record 记录
type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        map[string]*Value      `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 字段名 -> 值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_api_agility_data_service_v1_agility_data_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_api_agility_data_service_v1_agility_data_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_api_agility_data_service_v1_agility_data_proto_rawDescGZIP(), []int{11}
}

func (x *Record) GetFields() map[string]*Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Value 值类型
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Value_StringValue
	//	*Value_IntValue
	//	*Value_DoubleValue
	//	*Value_BoolValue
	//	*Value_BytesValue
	//	*Value_TimestampValue
	//	*Value_NullValue
	Value         isValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_api_agility_data_service_v1_agility_data_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_api_agility_data_service_v1_agility_data_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_api_agility_data_service_v1_agility_data_proto_rawDescGZIP(), []int{12}
}

func (x *Value) GetValue() isValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*Value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Value) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*Value_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *Value) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*Value_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Value) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*Value_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *Value) GetTimestampValue() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Value.(*Value_TimestampValue); ok {
			return x.TimestampValue
		}
	}
	return nil
}

func (x *Value) GetNullValue() NullValue {
	if x != nil {
		if x, ok := x.Value.(*Value_NullValue); ok {
			return x.NullValue
		}
	}
	return NullValue_NULL_VALUE
}

type isValue_Value interface {
	isValue_Value()
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type Value_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,3,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Value_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,5,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type Value_TimestampValue struct {
	TimestampValue *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp_value,json=timestampValue,proto3,oneof"`
}

type Value_NullValue struct {
	NullValue NullValue `protobuf:"varint,7,opt,name=null_value,json=nullValue,proto3,enum=api.agility_data.service.v1.NullValue,oneof"`
}

func (*Value_StringValue) isValue_Value() {}

func (*Value_IntValue) isValue_Value() {}

func (*Value_DoubleValue) isValue_Value() {}

func (*Value_BoolValue) isValue_Value() {}

func (*Value_BytesValue) isValue_Value() {}

func (*Value_TimestampValue) isValue_Value() {}

func (*Value_NullValue) isValue_Value() {}

// DataSourceInfo 数据源信息
type DataSourceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Driver        string                 `protobuf:"bytes,2,opt,name=driver,proto3" json:"driver,omitempty"` // 驱动类型：mysql, postgresql, oracle等
	Host          string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Database      string                 `protobuf:"bytes,5,opt,name=database,proto3" json:"database,omitempty"`
	Username      string                 `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataSourceInfo) Reset() {
	*x = DataSourceInfo{}
	mi := &file_api_agility_data_service_v1_agility_data_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataSourceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSourceInfo) ProtoMessage() {}

func (x *DataSourceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_agility_data_service_v1_agility_data_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSourceInfo.ProtoReflect.Descriptor instead.
func (*DataSourceInfo) Descriptor() ([]byte, []int) {
	return file_api_agility_data_service_v1_agility_data_proto_rawDescGZIP(), []int{13}
}

func (x *DataSourceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataSourceInfo) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *DataSourceInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *DataSourceInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DataSourceInfo) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *DataSourceInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DataSourceInfo) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *DataSourceInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *DataSourceInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_api_agility_data_service_v1_agility_data_proto protoreflect.FileDescriptor

const file_api_agility_data_service_v1_agility_data_proto_rawDesc = "" +
	"\n" +
	".api/agility_data/service/v1/agility_data.proto\x12\x1bapi.agility_data.service.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa4\x02\n" +
	"\vListRequest\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\x12(\n" +
	"\x10data_source_name\x18\x02 \x01(\tR\x0edataSourceName\x12L\n" +
	"\x06params\x18\x03 \x03(\v24.api.agility_data.service.v1.ListRequest.ParamsEntryR\x06params\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vresult_type\x18\x06 \x01(\tR\n" +
	"resultType\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xff\x01\n" +
	"\fListResponse\x12=\n" +
	"\arecords\x18\x01 \x03(\v2#.api.agility_data.service.v1.RecordR\arecords\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12\x18\n" +
	"\asuccess\x18\a \x01(\bR\asuccess\"\xd0\x01\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\x12(\n" +
	"\x10data_source_name\x18\x02 \x01(\tR\x0edataSourceName\x12K\n" +
	"\x06params\x18\x03 \x03(\v23.api.agility_data.service.v1.GetRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x89\x01\n" +
	"\vGetResponse\x12;\n" +
	"\x06record\x18\x01 \x01(\v2#.api.agility_data.service.v1.RecordR\x06record\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"\x8c\x02\n" +
	"\x0eExecuteRequest\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\x12(\n" +
	"\x10data_source_name\x18\x02 \x01(\tR\x0edataSourceName\x12O\n" +
	"\x06params\x18\x03 \x03(\v27.api.agility_data.service.v1.ExecuteRequest.ParamsEntryR\x06params\x122\n" +
	"\x15return_generated_keys\x18\x04 \x01(\bR\x13returnGeneratedKeys\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9c\x01\n" +
	"\x0fExecuteResponse\x12#\n" +
	"\rrows_affected\x18\x01 \x01(\x03R\frowsAffected\x12%\n" +
	"\x0egenerated_keys\x18\x02 \x03(\x03R\rgeneratedKeys\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\"\x92\x01\n" +
	"\tParamsMap\x12J\n" +
	"\x06params\x18\x01 \x03(\v22.api.agility_data.service.v1.ParamsMap.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9a\x01\n" +
	"\x13BatchExecuteRequest\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\x12(\n" +
	"\x10data_source_name\x18\x02 \x01(\tR\x0edataSourceName\x12G\n" +
	"\vparams_list\x18\x03 \x03(\v2&.api.agility_data.service.v1.ParamsMapR\n" +
	"paramsList\"\x83\x01\n" +
	"\x14BatchExecuteResponse\x12,\n" +
	"\x12rows_affected_list\x18\x01 \x03(\x03R\x10rowsAffectedList\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"A\n" +
	"\x15TestConnectionRequest\x12(\n" +
	"\x10data_source_name\x18\x01 \x01(\tR\x0edataSourceName\"z\n" +
	"\x16TestConnectionResponse\x12\x1c\n" +
	"\tconnected\x18\x01 \x01(\bR\tconnected\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x10response_time_ms\x18\x03 \x01(\x03R\x0eresponseTimeMs\"\xb0\x01\n" +
	"\x06Record\x12G\n" +
	"\x06fields\x18\x01 \x03(\v2/.api.agility_data.service.v1.Record.FieldsEntryR\x06fields\x1a]\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".api.agility_data.service.v1.ValueR\x05value:\x028\x01\"\xcd\x02\n" +
	"\x05Value\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fdouble_value\x18\x03 \x01(\x01H\x00R\vdoubleValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x12!\n" +
	"\vbytes_value\x18\x05 \x01(\fH\x00R\n" +
	"bytesValue\x12E\n" +
	"\x0ftimestamp_value\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x0etimestampValue\x12G\n" +
	"\n" +
	"null_value\x18\a \x01(\x0e2&.api.agility_data.service.v1.NullValueH\x00R\tnullValueB\a\n" +
	"\x05value\"\xf7\x01\n" +
	"\x0eDataSourceInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06driver\x18\x02 \x01(\tR\x06driver\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x1a\n" +
	"\bdatabase\x18\x05 \x01(\tR\bdatabase\x12\x1a\n" +
	"\busername\x18\x06 \x01(\tR\busername\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt*\x1b\n" +
	"\tNullValue\x12\x0e\n" +
	"\n" +
	"NULL_VALUE\x10\x002\xa4\x04\n" +
	"\vAgilityData\x12]\n" +
	"\x04List\x12(.api.agility_data.service.v1.ListRequest\x1a).api.agility_data.service.v1.ListResponse\"\x00\x12Z\n" +
	"\x03Get\x12'.api.agility_data.service.v1.GetRequest\x1a(.api.agility_data.service.v1.GetResponse\"\x00\x12f\n" +
	"\aExecute\x12+.api.agility_data.service.v1.ExecuteRequest\x1a,.api.agility_data.service.v1.ExecuteResponse\"\x00\x12u\n" +
	"\fBatchExecute\x120.api.agility_data.service.v1.BatchExecuteRequest\x1a1.api.agility_data.service.v1.BatchExecuteResponse\"\x00\x12{\n" +
	"\x0eTestConnection\x122.api.agility_data.service.v1.TestConnectionRequest\x1a3.api.agility_data.service.v1.TestConnectionResponse\"\x00BP\n" +
	"\x1bapi.agility_data.service.v1P\x01Z/lehu-data-center/api/agility_data/service/v1;v1b\x06proto3"

var (
	file_api_agility_data_service_v1_agility_data_proto_rawDescOnce sync.Once
	file_api_agility_data_service_v1_agility_data_proto_rawDescData []byte
)

func file_api_agility_data_service_v1_agility_data_proto_rawDescGZIP() []byte {
	file_api_agility_data_service_v1_agility_data_proto_rawDescOnce.Do(func() {
		file_api_agility_data_service_v1_agility_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_agility_data_service_v1_agility_data_proto_rawDesc), len(file_api_agility_data_service_v1_agility_data_proto_rawDesc)))
	})
	return file_api_agility_data_service_v1_agility_data_proto_rawDescData
}

var file_api_agility_data_service_v1_agility_data_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_agility_data_service_v1_agility_data_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_api_agility_data_service_v1_agility_data_proto_goTypes = []any{
	(NullValue)(0),                 // 0: api.agility_data.service.v1.NullValue
	(*ListRequest)(nil),            // 1: api.agility_data.service.v1.ListRequest
	(*ListResponse)(nil),           // 2: api.agility_data.service.v1.ListResponse
	(*GetRequest)(nil),             // 3: api.agility_data.service.v1.GetRequest
	(*GetResponse)(nil),            // 4: api.agility_data.service.v1.GetResponse
	(*ExecuteRequest)(nil),         // 5: api.agility_data.service.v1.ExecuteRequest
	(*ExecuteResponse)(nil),        // 6: api.agility_data.service.v1.ExecuteResponse
	(*ParamsMap)(nil),              // 7: api.agility_data.service.v1.ParamsMap
	(*BatchExecuteRequest)(nil),    // 8: api.agility_data.service.v1.BatchExecuteRequest
	(*BatchExecuteResponse)(nil),   // 9: api.agility_data.service.v1.BatchExecuteResponse
	(*TestConnectionRequest)(nil),  // 10: api.agility_data.service.v1.TestConnectionRequest
	(*TestConnectionResponse)(nil), // 11: api.agility_data.service.v1.TestConnectionResponse
	(*Record)(nil),                 // 12: api.agility_data.service.v1.Record
	(*Value)(nil),                  // 13: api.agility_data.service.v1.Value
	(*DataSourceInfo)(nil),         // 14: api.agility_data.service.v1.DataSourceInfo
	nil,                            // 15: api.agility_data.service.v1.ListRequest.ParamsEntry
	nil,                            // 16: api.agility_data.service.v1.GetRequest.ParamsEntry
	nil,                            // 17: api.agility_data.service.v1.ExecuteRequest.ParamsEntry
	nil,                            // 18: api.agility_data.service.v1.ParamsMap.ParamsEntry
	nil,                            // 19: api.agility_data.service.v1.Record.FieldsEntry
	(*timestamppb.Timestamp)(nil),  // 20: google.protobuf.Timestamp
}
var file_api_agility_data_service_v1_agility_data_proto_depIdxs = []int32{
	15, // 0: api.agility_data.service.v1.ListRequest.params:type_name -> api.agility_data.service.v1.ListRequest.ParamsEntry
	12, // 1: api.agility_data.service.v1.ListResponse.records:type_name -> api.agility_data.service.v1.Record
	16, // 2: api.agility_data.service.v1.GetRequest.params:type_name -> api.agility_data.service.v1.GetRequest.ParamsEntry
	12, // 3: api.agility_data.service.v1.GetResponse.record:type_name -> api.agility_data.service.v1.Record
	17, // 4: api.agility_data.service.v1.ExecuteRequest.params:type_name -> api.agility_data.service.v1.ExecuteRequest.ParamsEntry
	18, // 5: api.agility_data.service.v1.ParamsMap.params:type_name -> api.agility_data.service.v1.ParamsMap.ParamsEntry
	7,  // 6: api.agility_data.service.v1.BatchExecuteRequest.params_list:type_name -> api.agility_data.service.v1.ParamsMap
	19, // 7: api.agility_data.service.v1.Record.fields:type_name -> api.agility_data.service.v1.Record.FieldsEntry
	20, // 8: api.agility_data.service.v1.Value.timestamp_value:type_name -> google.protobuf.Timestamp
	0,  // 9: api.agility_data.service.v1.Value.null_value:type_name -> api.agility_data.service.v1.NullValue
	13, // 10: api.agility_data.service.v1.Record.FieldsEntry.value:type_name -> api.agility_data.service.v1.Value
	1,  // 11: api.agility_data.service.v1.AgilityData.List:input_type -> api.agility_data.service.v1.ListRequest
	3,  // 12: api.agility_data.service.v1.AgilityData.Get:input_type -> api.agility_data.service.v1.GetRequest
	5,  // 13: api.agility_data.service.v1.AgilityData.Execute:input_type -> api.agility_data.service.v1.ExecuteRequest
	8,  // 14: api.agility_data.service.v1.AgilityData.BatchExecute:input_type -> api.agility_data.service.v1.BatchExecuteRequest
	10, // 15: api.agility_data.service.v1.AgilityData.TestConnection:input_type -> api.agility_data.service.v1.TestConnectionRequest
	2,  // 16: api.agility_data.service.v1.AgilityData.List:output_type -> api.agility_data.service.v1.ListResponse
	4,  // 17: api.agility_data.service.v1.AgilityData.Get:output_type -> api.agility_data.service.v1.GetResponse
	6,  // 18: api.agility_data.service.v1.AgilityData.Execute:output_type -> api.agility_data.service.v1.ExecuteResponse
	9,  // 19: api.agility_data.service.v1.AgilityData.BatchExecute:output_type -> api.agility_data.service.v1.BatchExecuteResponse
	11, // 20: api.agility_data.service.v1.AgilityData.TestConnection:output_type -> api.agility_data.service.v1.TestConnectionResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_agility_data_service_v1_agility_data_proto_init() }
func file_api_agility_data_service_v1_agility_data_proto_init() {
	if File_api_agility_data_service_v1_agility_data_proto != nil {
		return
	}
	file_api_agility_data_service_v1_agility_data_proto_msgTypes[12].OneofWrappers = []any{
		(*Value_StringValue)(nil),
		(*Value_IntValue)(nil),
		(*Value_DoubleValue)(nil),
		(*Value_BoolValue)(nil),
		(*Value_BytesValue)(nil),
		(*Value_TimestampValue)(nil),
		(*Value_NullValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_agility_data_service_v1_agility_data_proto_rawDesc), len(file_api_agility_data_service_v1_agility_data_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_agility_data_service_v1_agility_data_proto_goTypes,
		DependencyIndexes: file_api_agility_data_service_v1_agility_data_proto_depIdxs,
		EnumInfos:         file_api_agility_data_service_v1_agility_data_proto_enumTypes,
		MessageInfos:      file_api_agility_data_service_v1_agility_data_proto_msgTypes,
	}.Build()
	File_api_agility_data_service_v1_agility_data_proto = out.File
	file_api_agility_data_service_v1_agility_data_proto_goTypes = nil
	file_api_agility_data_service_v1_agility_data_proto_depIdxs = nil
}
