// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: api/agility_data/service/v1/agility_data.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgilityData_List_FullMethodName           = "/api.agility_data.service.v1.AgilityData/List"
	AgilityData_Get_FullMethodName            = "/api.agility_data.service.v1.AgilityData/Get"
	AgilityData_Execute_FullMethodName        = "/api.agility_data.service.v1.AgilityData/Execute"
	AgilityData_BatchExecute_FullMethodName   = "/api.agility_data.service.v1.AgilityData/BatchExecute"
	AgilityData_TestConnection_FullMethodName = "/api.agility_data.service.v1.AgilityData/TestConnection"
)

// AgilityDataClient is the client API for AgilityData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 敏捷数据服务
type AgilityDataClient interface {
	// List 查询列表数据
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	// Get 查询单条数据
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// Execute 执行SQL
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	// BatchExecute 批量执行
	BatchExecute(ctx context.Context, in *BatchExecuteRequest, opts ...grpc.CallOption) (*BatchExecuteResponse, error)
	// TestConnection 测试连接
	TestConnection(ctx context.Context, in *TestConnectionRequest, opts ...grpc.CallOption) (*TestConnectionResponse, error)
}

type agilityDataClient struct {
	cc grpc.ClientConnInterface
}

func NewAgilityDataClient(cc grpc.ClientConnInterface) AgilityDataClient {
	return &agilityDataClient{cc}
}

func (c *agilityDataClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, AgilityData_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agilityDataClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, AgilityData_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agilityDataClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, AgilityData_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agilityDataClient) BatchExecute(ctx context.Context, in *BatchExecuteRequest, opts ...grpc.CallOption) (*BatchExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchExecuteResponse)
	err := c.cc.Invoke(ctx, AgilityData_BatchExecute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agilityDataClient) TestConnection(ctx context.Context, in *TestConnectionRequest, opts ...grpc.CallOption) (*TestConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestConnectionResponse)
	err := c.cc.Invoke(ctx, AgilityData_TestConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgilityDataServer is the server API for AgilityData service.
// All implementations must embed UnimplementedAgilityDataServer
// for forward compatibility.
//
// 敏捷数据服务
type AgilityDataServer interface {
	// List 查询列表数据
	List(context.Context, *ListRequest) (*ListResponse, error)
	// Get 查询单条数据
	Get(context.Context, *GetRequest) (*GetResponse, error)
	// Execute 执行SQL
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	// BatchExecute 批量执行
	BatchExecute(context.Context, *BatchExecuteRequest) (*BatchExecuteResponse, error)
	// TestConnection 测试连接
	TestConnection(context.Context, *TestConnectionRequest) (*TestConnectionResponse, error)
	mustEmbedUnimplementedAgilityDataServer()
}

// UnimplementedAgilityDataServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgilityDataServer struct{}

func (UnimplementedAgilityDataServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedAgilityDataServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedAgilityDataServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedAgilityDataServer) BatchExecute(context.Context, *BatchExecuteRequest) (*BatchExecuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchExecute not implemented")
}
func (UnimplementedAgilityDataServer) TestConnection(context.Context, *TestConnectionRequest) (*TestConnectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestConnection not implemented")
}
func (UnimplementedAgilityDataServer) mustEmbedUnimplementedAgilityDataServer() {}
func (UnimplementedAgilityDataServer) testEmbeddedByValue()                     {}

// UnsafeAgilityDataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgilityDataServer will
// result in compilation errors.
type UnsafeAgilityDataServer interface {
	mustEmbedUnimplementedAgilityDataServer()
}

func RegisterAgilityDataServer(s grpc.ServiceRegistrar, srv AgilityDataServer) {
	// If the following call pancis, it indicates UnimplementedAgilityDataServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgilityData_ServiceDesc, srv)
}

func _AgilityData_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgilityDataServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgilityData_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgilityDataServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgilityData_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgilityDataServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgilityData_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgilityDataServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgilityData_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgilityDataServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgilityData_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgilityDataServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgilityData_BatchExecute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgilityDataServer).BatchExecute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgilityData_BatchExecute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgilityDataServer).BatchExecute(ctx, req.(*BatchExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgilityData_TestConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgilityDataServer).TestConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgilityData_TestConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgilityDataServer).TestConnection(ctx, req.(*TestConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgilityData_ServiceDesc is the grpc.ServiceDesc for AgilityData service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgilityData_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.agility_data.service.v1.AgilityData",
	HandlerType: (*AgilityDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _AgilityData_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _AgilityData_Get_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _AgilityData_Execute_Handler,
		},
		{
			MethodName: "BatchExecute",
			Handler:    _AgilityData_BatchExecute_Handler,
		},
		{
			MethodName: "TestConnection",
			Handler:    _AgilityData_TestConnection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/agility_data/service/v1/agility_data.proto",
}
